### ISSUE TITLE
matrixy requires parrot_nqp and hence cannot use parrot's older than 1.6.0

### ISSUE THREAD

**Issue by leto** [Whiteknight/matrixy#1]
/usr/local/bin/parrot  /usr/local/lib/parrot/1.5.0-devel/library/PGE/Perl6Grammar.pbc  --output=src/gen_grammar.pir  src/parser/grammar.pg  src/parser/grammar-oper.pg

/usr/local/bin/parrot_nqp --output=src/gen_actions.pir  --target=pir src/parser/actions.pm

/usr/local/bin/parrot_nqp: not found

**Comment by leto** [comment]
Configure should check if it can find parrot_nqp and complain if it can't

**Comment by darbelo** [comment]
As of 04fc3520d0ed9de3be44771dc98914d0ca60e578 we don't use the parrot_nqp fakecutable anymore, we simply invoke parrot to run nqp.pbc which should work for any correctly installed parrot.
